{% set name = "mplhep" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fdc7e91986500c6921057e7fe1bab7d159d17761c5e7bfb9af01c3f3234e5116

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base >=3.2
    - numpy >=1.16.0
    - packaging
    - python >=3.6
    - requests >=2.21,<3
    - scipy >=1.1.0

test:
  imports:
    - mplhep

about:
  home: https://github.com/scikit-hep/mplhep
  license: MIT
  license_file: LICENSE
  summary: Matplotlib styles for HEP
  dev_url: https://github.com/scikit-hep/mplhep

extra:
  recipe-maintainers:
    - andrzejnovak
    - chrisburr
