{% set name = "mplhep" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f4886c402afb121c5399f91315f47c01367a874376ed84e8801484b1f4e17a3c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - matplotlib-base >=3.4
    - numpy >=1.16.0
    - packaging
    - python >=3.7
    - requests >=2.21,<3
    - scipy >=1.1.0
    - mplhep_data

test:
  imports:
    - mplhep

about:
  home: https://github.com/scikit-hep/mplhep
  license: MIT
  license_file: LICENSE
  summary: Matplotlib styles for HEP
  dev_url: https://github.com/scikit-hep/mplhep

extra:
  recipe-maintainers:
    - andrzejnovak
    - conda-forge/scikit-hep
