{% set name = "mplhep" %}
{% set version = "0.3.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d9eace4be35224493f250c73f03eee40aaba5317ebef5fda194225fa843e3c7e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - matplotlib-base >=3.4
    - numpy >=1.16.0
    - packaging
    - python >=3.7
    - mplhep_data
    - uhi >=0.2.0

test:
  imports:
    - mplhep

about:
  home: https://github.com/scikit-hep/mplhep
  license: MIT
  license_file: LICENSE
  summary: Matplotlib styles for HEP
  dev_url: https://github.com/scikit-hep/mplhep

extra:
  recipe-maintainers:
    - andrzejnovak
    - conda-forge/scikit-hep
