{% set name = "mplhep" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f849fe94146afa791e271d19cbbf1e6676b1cc64edf18c36e923a095b467f4fc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - matplotlib-base >=3.2
    - numpy >=1.16.0
    - packaging
    - python
    - requests >=2.21,<3
    - scipy >=1.1.0

test:
  imports:
    - mplhep

about:
  home: https://github.com/scikit-hep/mplhep
  license: MIT
  license_file: LICENSE
  summary: Matplotlib styles for HEP
  dev_url: https://github.com/scikit-hep/mplhep

extra:
  recipe-maintainers:
    - andrzejnovak
    - chrisburr
