{% set name = "mplhep" %}
{% set version = "0.3.29" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d05eff75da2b76892674eec2a9382df166e0a31a2c933835271b1abea84c0ac7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
  run:
    - matplotlib-base >=3.4
    - numpy >=1.16.0
    - packaging
    - python >=3.7
    - mplhep_data
    - uhi >=0.2.0

test:
  imports:
    - mplhep

about:
  home: https://github.com/scikit-hep/mplhep
  license: MIT
  license_file: LICENSE
  summary: Matplotlib styles for HEP
  dev_url: https://github.com/scikit-hep/mplhep

extra:
  recipe-maintainers:
    - andrzejnovak
    - conda-forge/scikit-hep
